# Form implementation generated from reading ui file 'gui/Settings.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 260)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.OBSAddr = QtWidgets.QLineEdit(parent=self.tab)
        self.OBSAddr.setObjectName("OBSAddr")
        self.verticalLayout_2.addWidget(self.OBSAddr)
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.OBSPort = QtWidgets.QSpinBox(parent=self.tab)
        self.OBSPort.setMaximum(65535)
        self.OBSPort.setObjectName("OBSPort")
        self.verticalLayout_2.addWidget(self.OBSPort)
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.OBSPass = QtWidgets.QLineEdit(parent=self.tab)
        self.OBSPass.setObjectName("OBSPass")
        self.verticalLayout_2.addWidget(self.OBSPass)
        self.SaveButton = QtWidgets.QPushButton(parent=self.tab)
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout_2.addWidget(self.SaveButton)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.OBSAddr)
        MainWindow.setTabOrder(self.OBSAddr, self.OBSPort)
        MainWindow.setTabOrder(self.OBSPort, self.OBSPass)
        MainWindow.setTabOrder(self.OBSPass, self.SaveButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "OBS Address"))
        self.label_2.setText(_translate("MainWindow", "OBS Port"))
        self.label_3.setText(_translate("MainWindow", "OBS Password"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Preferences"))
