name: Announce Release on Discord
on:
  release:
    types: [published]
jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Changelog Section
        id: changelog
        shell: pwsh
        run: |
          $tagVersion = "${{ github.event.release.tag_name }}"
          $version = $tagVersion -replace '^[vb]', ''
          $changelogContent = Get-Content -Path "CHANGELOG.md" -Raw
          $pattern1 = "(?s)## \[$version\].*?(?=## \[|$)"
          $pattern2 = "(?s)## \[$tagVersion\].*?(?=## \[|$)"
          $match = [regex]::Match($changelogContent, $pattern1)
          if (-not $match.Success) {
            $match = [regex]::Match($changelogContent, $pattern2)
          }
          if ($match.Success) {
            $sectionContent = $match.Value -replace "^## \[.*?\].*?\r?\n", "" -replace "\r?\n$", ""
            $changelog = $sectionContent.Trim()
          } else {
            $changelog = "No specific changelog found for this version. See commit history below."
          }
          "CHANGELOG_CONTENT<<EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          $changelog | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Announce Release on Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          changelog="${{ steps.changelog.outputs.CHANGELOG_CONTENT }}"
          if [ -z "$changelog" ]; then
            changelog="There aren't any changelog entries for this release."
          fi
          version="${{ github.event.release.tag_name }}"
          message="<@&1346974681399427153>

          ${REPO_NAME} ${version}

          ${changelog}

          <#1347670260844855376>"
          payload=$(jq -n --arg content "$message" '{content: $content}')
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$payload" \
               "$DISCORD_WEBHOOK"
