on:
  push:
    branches:
      - main
jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest / ..... etc>
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'GoExport.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'GoExport'
          options: --onefile, --name "GoExport"