name: Package Application with PyInstaller
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.13'
            
            - name: Download FFMPEG
              run: |
                curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
                tar -xf ffmpeg.zip -C dependencies
                move dependencies\ffmpeg-master-latest-win64-gpl dependencies\ffmpeg
                rm ffmpeg.zip
            
            - name: Download ungoogled-chromium
              run: |
                curl -L -o ungoogled-chromium.zip https://github.com/tangalbert919/ungoogled-chromium-binaries/releases/download/87.0.4280.67-1/ungoogled-chromium_87.0.4280.67-1.1_windows-x64.zip
                tar -xf ungoogled-chromium.zip -C dependencies\ungoogled-chromium
                move dependencies\ungoogled-chromium\ungoogled-chromium_87.0.4280.67-1.1_windows-x64 dependencies\ungoogled-chromium\ungoogled-chromium
                rm ungoogled-chromium.zip
            
            - name: Download chromedriver
              run: |
                curl -L -o chromedriver.zip https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_win32.zip
                tar -xf chromedriver.zip -C dependencies\chromedriver
                move dependencies\chromedriver dependencies\chromedriver
                rm chromedriver.zip

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Package Application with PyInstaller
              run: |
                  pyinstaller GoExport.spec

            - name: Copy files to dist folder
              run: |
                copy readme.md dist\
                copy LICENSE dist\
                copy uninstall.bat dist\
                xcopy assets dist\assets /E /I /Q /Y
                xcopy libs dist\libs /E /I /Q /Y

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Windows-exe
                  path: dist/