name: Package Application with PyInstaller
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.13'
            
            - name: Download FFMPEG
              run: |
                Invoke-WebRequest -Uri https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip -OutFile ffmpeg.zip
                Expand-Archive -Path ffmpeg.zip -DestinationPath dependencies\ffmpeg
            
            - name: Download ungoogled-chromium
              run: |
                Invoke-WebRequest -Uri https://github.com/tangalbert919/ungoogled-chromium-binaries/releases/download/87.0.4280.67-1/ungoogled-chromium_87.0.4280.67-1.1_windows-x64.zip -OutFile ungoogled-chromium.zip
                Expand-Archive -Path ungoogled-chromium.zip -DestinationPath dependencies\ungoogled-chromium
            
            - name: Download chromedriver
              run: |
                Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_win32.zip -OutFile chromedriver.zip
                Expand-Archive -Path chromedriver.zip -DestinationPath dependencies\chromedriver

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Package Application with PyInstaller
              run: |
                  pyinstaller GoExport.spec

            - name: Copy files to dist folder
              run: |
                copy readme.md dist\
                copy LICENSE dist\
                copy uninstall.bat dist\
                xcopy assets dist\assets /E /I /Q /Y
                xcopy libs dist\libs /E /I /Q /Y

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Windows-exe
                  path: dist/