name: Package Application with PyInstaller
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Package Application with PyInstaller
              run: |
                  pyinstaller GoExport.spec

            - name: Copy files to dist folder
              run: |
                copy readme.md dist\
                copy LICENSE dist\
                copy uninstall.bat dist\
                xcopy assets dist\assets /E /I /Q /Y
                xcopy libs dist\libs /E /I /Q /Y

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Windows-exe
                  path: dist/