name: Build, Release, and Notify
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller GoExport.spec

      - name: Copy required files to dist
        run: |
          mkdir -p dist/assets
          mkdir -p dist/server
          cp readme.md dist/
          cp LICENSE dist/
          cp -r assets/* dist/assets/
          cp -r server/* dist/server/

      - name: Build installer (Windows only)
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        if: matrix.os == 'windows-latest'
        with:
          path: setup\GoExport.iss
          options: /O+

      - name: Archive Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czf goexport_linux_portable_amd64.tar.gz -C dist .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: |
            goexport_linux_portable_amd64.tar.gz
            goexport_win_installer_amd64.exe
            dist/**
          if-no-files-found: ignore

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files
        run: ls -R artifacts

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/**/goexport_linux_portable_amd64.tar.gz
            artifacts/**/goexport_win_installer_amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  changelog:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      changelog: ${{ steps.extract.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract changelog
        id: extract
        run: |
          section=$(awk '/## \['"${GITHUB_REF_NAME#v}"'\]/{flag=1; next} /^## /{flag=0} flag' CHANGELOG.md)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$section" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  discord_notify:
    runs-on: ubuntu-latest
    needs: [release, changelog]
    steps:
      - name: Notify Discord
        run: |
          repo_name="${GITHUB_REPOSITORY#*/}"
          tag="${GITHUB_REF_NAME}"

          changelog="${{ needs.changelog.outputs.changelog }}"

          payload=$(jq -n \
            --arg role "<@&1346974681399427153>" \
            --arg repo "$repo_name" \
            --arg tag "$tag" \
            --arg changelog "$changelog" \
            --arg channel "<#1347670260844855376>" \
            '{content: "\($role)\n\n# \($repo) - \($tag)\n\n\($changelog)\n\n\($channel)"}')

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "$payload" \
            ${{ secrets.DISCORD_WEBHOOK }}
