name: Build, Release, and Notify

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller GoExport.spec

      - name: Copy required files to dist
        run: |
          mkdir -p dist/assets
          mkdir -p dist/server
          cp readme.md dist/
          cp LICENSE dist/
          cp -r assets/* dist/assets/
          cp -r server/* dist/server/

      - name: Build installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        if: matrix.os == 'windows-latest'
        with:
          path: setup\GoExport.iss
          options: /O+

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: dist/
          if-no-files-found: ignore

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/app-ubuntu-latest/goexport_linux_amd64.tar.gz
            dist/app-windows-latest/GoExport.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  changelog:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      changelog: ${{ steps.extract.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract changelog
        id: extract
        run: |
          section=$(awk '/## \['"${GITHUB_REF_NAME#v}"'\]/{flag=1; next} /^## /{flag=0} flag' CHANGELOG.md)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$section" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  discord_notify:
    runs-on: ubuntu-latest
    needs: release_assets
    steps:
      - name: Notify Discord
        run: |
          repo_name="${GITHUB_REPOSITORY#*/}"
          tag="${GITHUB_REF_NAME}"

          # Pull in the changelog from the changelog job
          changelog="${{ needs.changelog.outputs.changelog }}"

          # Escape properly for JSON
          changelog_escaped=$(jq -Rs . <<< "$changelog")

          payload=$(jq -n \
            --arg role "<@&1346974681399427153>" \
            --arg repo "$repo_name" \
            --arg tag "$tag" \
            --argjson changelog "$changelog_escaped" \
            --arg channel "<#1347670260844855376>" \
            '{content: "\($role)\n\n# \($repo) - \($tag)\n\n\($changelog)\n\n\($channel)"}')

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "$payload" \
            ${{ secrets.DISCORD_WEBHOOK }}
